apiVersion: v1
kind: Service
metadata:
  name: argocd-app-service
  labels:
    app: argocd-app
spec:
  type: LoadBalancer
  ports:
    - port: 8888        
      targetPort: 8888  
  selector:
    app: argocd-app
