apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
  labels:
    app: argocd-app
spec:
  selector:
    matchLabels:
      app: argocd-app
  replicas: 1
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: wilsplayground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
